name: finalsalesrep
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # UI and Material Design
  cupertino_icons: ^1.0.8

  # Networking
  http: ^1.3.0

  # Date/time handling
  date_time: ^0.12.0

  # Local storage
  shared_preferences: ^2.1.0

  # Firebase services
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5

  # Location services
  geolocator: ^14.0.1

  # Image handling
  image_picker: ^1.1.2

  # State management (optional but common)
  provider: ^6.1.5

  # Routing (optional, advanced navigation)
  go_router: ^13.1.0

  # Logging
  logger: ^2.0.2

  # Loading spinners
  flutter_spinkit: ^5.2.0
  intl: any
  flutter_localizations:
    sdk: flutter
  geocoding: ^4.0.0
  url_launcher: ^6.3.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.8

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/

    
flutter_launcher_icons: 
  android: true
  ios: true
  image_path: "assets/esanchaya_survey_removebg.png"
  min_sdk_android: 21
  min_sdk_ios: 11.0
  remove_alpha_ios: true
  android_gravity: center
  ios_content_mode: center
  fullscreen: true
  web:
    generate: false
    android_gravity: center

    android_scale_type: fitXY
    ios_content_mode: scaleToFill

    android_image_scale: "3.0"






